#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
$HOME/.config/polybar/launch.sh &

bspc config border_width         3
bspc config window_gap          30

bspc config -m focused top_padding 34
bspc config focused_border_color "#dedede"
bspc config normal_border_color "#555555"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true